# Generated by Django 2.1.1 on 2018-10-15 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_userbase_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAriseTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelstartplace', models.CharField(max_length=50, null=True)),
                ('travelstrattime', models.DateTimeField()),
                ('travelendtime', models.DateTimeField()),
                ('menbers', models.IntegerField()),
                ('linkname', models.CharField(max_length=30)),
                ('linknumber', models.CharField(max_length=30)),
                ('destribe', models.CharField(max_length=100)),
                ('pubtime', models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 55, 34, 852178))),
                ('initiator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
