# Generated by Django 2.1.1 on 2018-10-15 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0002_auto_20181015_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 58, 29, 966343)),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='traval.UserAriseTravel'),
        ),
    ]
