# Generated by Django 2.1.1 on 2018-10-15 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userbase_icon'),
        ('traval', '0003_auto_20181015_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJoinTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jointime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 59, 18, 804891)),
        ),
        migrations.AddField(
            model_name='userjointravel',
            name='joinTravel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traval.UserAriseTravel'),
        ),
        migrations.AddField(
            model_name='userjointravel',
            name='joiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase'),
        ),
    ]
