# Generated by Django 2.1.1 on 2018-10-18 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0004_auto_20181015_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 10, 2, 18, 622917)),
        ),
    ]
