# Generated by Django 2.1.1 on 2018-10-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0009_auto_20181017_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 13, 44, 32, 682398)),
        ),
    ]
