# Generated by Django 2.1.1 on 2018-10-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0005_auto_20181018_1002'),
        ('traval', '0010_auto_20181018_1344'),
    ]

    operations = [
    ]
