# Generated by Django 2.1.1 on 2018-10-22 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0011_merge_20181020_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 18, 18, 42, 212607)),
        ),
    ]
