# Generated by Django 2.1.1 on 2018-10-22 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0012_auto_20181022_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 18, 45, 58, 248128)),
        ),
    ]
