# Generated by Django 2.1.1 on 2018-10-22 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0013_auto_20181022_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 19, 7, 0, 353652)),
        ),
    ]
