# Generated by Django 2.1.1 on 2018-10-24 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0016_auto_20181024_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 9, 55, 42, 933591)),
        ),
    ]
