# Generated by Django 2.1.1 on 2018-10-24 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0017_auto_20181024_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='addressurl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 10, 2, 42, 910811)),
        ),
    ]
