# Generated by Django 2.1.1 on 2018-10-24 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0018_auto_20181024_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplace',
            name='addressurl',
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 10, 41, 26, 80486)),
        ),
    ]
