# Generated by Django 2.1.1 on 2018-10-24 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0019_auto_20181024_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(default='', max_length=20)),
                ('iconurl', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 10, 47, 26, 476016)),
        ),
    ]
