# Generated by Django 2.1.1 on 2018-10-30 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0021_auto_20181024_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarisetravel',
            name='pubtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 16, 13, 4, 592472)),
        ),
    ]
