# Generated by Django 2.1.1 on 2018-10-18 02:02

from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 2.1.1 on 2018-10-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_userbase_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aritical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AriticalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=500)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('artical', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boke.Aritical')),
                ('commener', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
        migrations.CreateModel(
            name='ArticalStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('artical', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boke.Aritical')),
                ('liker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
        migrations.AddField(
            model_name='aritical',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boke.AriticalType'),
        ),
        migrations.AddField(
            model_name='aritical',
            name='yonghu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase'),
        ),
    ]
