# Generated by Django 2.1.1 on 2018-10-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userbase_icon'),
        ('boke', '0003_articalcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('artical', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boke.Aritical')),
                ('liker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
