# Generated by Django 2.1.1 on 2018-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0004_articalstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='articalcomment',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
