# Generated by Django 2.1.1 on 2018-10-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.IntegerField(max_length=30)),
                ('strictname', models.IntegerField(max_length=50)),
            ],
        ),
    ]
