# Generated by Django 2.1.1 on 2018-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='strictname',
            field=models.CharField(max_length=50),
        ),
    ]
