# Generated by Django 2.1.1 on 2018-10-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_citystore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=30)),
                ('carname', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('cartype', models.CharField(max_length=30)),
                ('storeid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.CityStore')),
            ],
        ),
    ]
