# Generated by Django 2.1.1 on 2018-10-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chexi', models.CharField(max_length=30)),
                ('niandaikuan', models.CharField(max_length=30)),
                ('peizhikun', models.CharField(max_length=30)),
                ('sitenum', models.CharField(max_length=100)),
                ('doornum', models.CharField(max_length=30)),
                ('oiltype', models.CharField(max_length=30)),
                ('changespeed', models.CharField(max_length=30)),
                ('pailiang', models.CharField(max_length=30)),
                ('oilnum', models.CharField(max_length=30)),
                ('qudong', models.CharField(max_length=30)),
                ('oilcaptiy', models.CharField(max_length=30)),
                ('carwindow', models.CharField(max_length=30)),
                ('sitetype', models.CharField(max_length=30)),
                ('musicnum', models.CharField(max_length=30)),
                ('isqinang', models.CharField(max_length=30)),
                ('isdaocheleida', models.CharField(max_length=30)),
                ('isgps', models.CharField(max_length=30)),
                ('isdvd', models.CharField(max_length=30)),
                ('jinqixingshi', models.CharField(max_length=30)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.CarBase')),
            ],
        ),
    ]
