# Generated by Django 2.1.1 on 2018-10-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cardetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbase',
            name='price',
            field=models.IntegerField(),
        ),
    ]
