# Generated by Django 2.1.1 on 2018-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20181015_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbase',
            name='carimg',
            field=models.CharField(default='丰田致炫.jpg', max_length=50),
        ),
    ]
