# Generated by Django 2.1.1 on 2018-10-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=100)),
                ('idcard', models.CharField(max_length=100)),
                ('idcardtime', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('urgentname', models.CharField(max_length=30)),
                ('urgenttel', models.CharField(max_length=30, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
