# Generated by Django 2.1.1 on 2018-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
