# Generated by Django 2.1.1 on 2018-10-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20181015_0909'),
        ('user', '0004_orderstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.CarBase')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
