# Generated by Django 2.1.1 on 2018-10-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20181015_0909'),
        ('user', '0005_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returncarplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.CityStore')),
            ],
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='car',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='yonghu',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
