# Generated by Django 2.1.1 on 2018-10-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181015_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='orderstate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.OrderState'),
        ),
    ]
