# Generated by Django 2.1.1 on 2018-10-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserIcon'),
        ),
    ]
