# Generated by Django 2.1.1 on 2018-10-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181018_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.CharField(max_length=20)),
                ('back', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
