# Generated by Django 2.1.1 on 2018-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdriver',
            name='back',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdriver',
            name='face',
            field=models.CharField(max_length=50),
        ),
    ]
