# Generated by Django 2.1.1 on 2018-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181022_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='iconurl',
            field=models.CharField(max_length=50),
        ),
    ]
