# Generated by Django 2.1.1 on 2018-10-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181022_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconname', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserBase')),
            ],
        ),
    ]
