# Generated by Django 2.1.1 on 2018-10-24 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_historyicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyicon',
            name='add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
